import {
  ArrowDown,
  ArrowRight,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  XCircle,
  Copy,
  AlignJustify,
  Columns3,
  LayoutGrid,
  GripVertical,
  Layers,
  Pencil,
  ChevronDown,
  Filter,
  ListFilter,
  FilterX,
  ChevronsLeft,
  Maximize,
  Minimize,
  ChevronsDown,
  ChevronsRight,
  MoreHorizontal,
  MoreVertical,
  Pin,
  RotateCcw,
  Save,
  Search,
  SearchX,
  ArrowUpDown,
  ArrowLeftRight,
  Eye,
  EyeOff,
} from 'lucide-react';

export const MRT_Default_Icons = {
  ArrowDownwardIcon: ArrowDown,
  ArrowRightIcon: ArrowRight,
  CancelIcon: XCircle,
  ChevronLeftIcon: ChevronLeft,
  ChevronRightIcon: ChevronRight,
  ClearAllIcon: ChevronsUpDown,
  CloseIcon: X,
  ContentCopy: Copy,
  DensityLargeIcon: AlignJustify,
  DensityMediumIcon: Columns3,
  DensitySmallIcon: LayoutGrid,
  DragHandleIcon: GripVertical,
  DynamicFeedIcon: Layers,
  EditIcon: Pencil,
  ExpandMoreIcon: ChevronDown,
  FilterAltIcon: Filter,
  FilterListIcon: ListFilter,
  FilterListOffIcon: FilterX,
  FirstPageIcon: ChevronsLeft,
  FullscreenExitIcon: Minimize,
  FullscreenIcon: Maximize,
  KeyboardDoubleArrowDownIcon: ChevronsDown,
  LastPageIcon: ChevronsRight,
  MoreHorizIcon: MoreHorizontal,
  MoreVertIcon: MoreVertical,
  PushPinIcon: Pin,
  RestartAltIcon: RotateCcw,
  SaveIcon: Save,
  SearchIcon: Search,
  SearchOffIcon: SearchX,
  SortIcon: ArrowUpDown,
  SyncAltIcon: ArrowLeftRight,
  ViewColumnIcon: Eye,
  VisibilityOffIcon: EyeOff,
} as const;

export type MRT_Icons = Record<keyof typeof MRT_Default_Icons, any>;
